### ISSUE TITLE
Missing technical requirements from Lab#3

### ISSUE THREAD

**Issue by elaewin** [EvitaAFD/twitter-client#9]
You are still missing the following technical requirements: 
* Create a 2nd UIViewController that shows an individual tweet in detail
* Upon clicking a tweet, your interface should push to another UIViewController that displays the tweet's details, via a storyboard segue, using labels to present the tweet details to the user instead of print() statements. Also:

  * If the tweet that was selected is a retweet, you should let the user know in some way.

* Create a ProfileViewController that when presented, shows the logged in user's profile information. Utilize the NavigationBar to add a button to present this new viewController. This can be achieved using the getOAuthUser method we wrote yesterday to get the current user's information.

**Comment by EvitaAFD** [comment]
These are present in the most recent lab- PR 8-10
